### ISSUE TITLE
UICollectionView上的使用问题

### ISSUE THREAD

**Issue by TheLittleBoy** [JackTeam/XHImageViewer#7]
用此HXImageViewer显示UICollectionViewCell上的图片时，图片被拉伸的特别大，不知道时什么原因引起 的。

**Comment by xhzengAIB** [comment]
可以使用的，应该是你在UICollectionView上的UIImageView的ContentMode导致的哦！

**Comment by xhzengAIB** [comment]
具体里面看这里
https://github.com/xhzengAIB/MessageDisplayKit

里面朋友圈的功能就是用这个做的

**Comment by TheLittleBoy** [comment]
先前应该做过各种尝试，难道代码更新了？

**Comment by xhzengAIB** [comment]
应该是没有更新的！具体你那边的问题，我觉得可能是iOS7的新特性导致的，比如ExtenLayout  aujustScroll等等
