### ISSUE TITLE
救助，使用XHImageViewer时出现问题。

### ISSUE THREAD

**Issue by XZAKE** [JackTeam/XHImageViewer#8]
救助，使用XHImageViewer时，左右滑动时会执行到XHImageViewer 的(void)handlePanGestureRecognizer:(UIPanGestureRecognizer *)sender 方法，但是demo上却不执行，本身左右滑动应该是UIScrollView 翻页，因为这个原因导致我不是左右翻看图片。

**Comment by xhzengAIB** [comment]
是不是手势冲突的原因？
你可以尝试在UIRecognizeGesture的Delegate方法里面做判断就好了！
