### ISSUE TITLE
请问下面的那条信息栏能自定义吗

### ISSUE THREAD

**Issue by kilik52** [JackTeam/XHImageViewer#9]
你好，我用Pod，请问下面的那条信息栏能自定义吗

**Comment by xhzengAIB** [comment]
可以自定的

**Comment by xhzengAIB** [comment]
https://github.com/JackTeam/XHImageViewer/blob/master/Source/Views/XHImageViewer.h#L32

**Comment by xhzengAIB** [comment]
上下工具条都可以
